name: authenticator_flutter
description: Flutter client SDK for Authenticator. Connects seamlessly to Laravel Authenticator API with secure storage, PIN privacy lock, OTP, and 2FA.
version: 1.0.0
homepage: https://github.com/ataurbdx/authenticator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
